micronaut:
  application:
    name: demo

  server:
    port: 8081

datasources:
  default:
    url: jdbc:mysql://localhost:3306/ITS
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ""

jpa:
  default:
    packages-to-scan:
      - 'com.example'
    properties:
      hibernate:
      hbm2ddl:
        auto: update
      show_sql: true
