micronaut:
  application:
    name: demo

  server:
    port: 8081

  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
              jws-algorithm: HS256

datasources:
  default:
    url: jdbc:mysql://localhost:3306/AP
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ""


jpa:
  default:
    entity-scan:
      packages:
        - 'com.example.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true